from textprocess.modifiers.modifiers import Modifiers
from textprocess.modifiers.synonymmodifier import SynonymModifier
from textprocess.modifiers.indirectordermodifier import IndirectOrderModifier
from textprocess.modifiers.synonymindirectmodifier import SynonymIndirectModifier
